// <auto-generated />
using System;
using ExamenPOO_U2.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenPOO_U2.Migrations
{
    [DbContext(typeof(PlanillaDbContext))]
    partial class PlanillaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ExamenPOO_U2.Database.Entities.DetailSheetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal>("Bonificaciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("bonificaciones");

                    b.Property<string>("Comentarios")
                        .HasColumnType("TEXT")
                        .HasColumnName("comentarios");

                    b.Property<decimal>("Deducciones")
                        .HasColumnType("TEXT")
                        .HasColumnName("deducciones");

                    b.Property<decimal>("HorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("horas_extra");

                    b.Property<decimal>("MontoHorasExtra")
                        .HasColumnType("TEXT")
                        .HasColumnName("monto_horas_extra");

                    b.Property<decimal>("SalarioBase")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("SalarioNeto")
                        .HasColumnType("TEXT")
                        .HasColumnName("salario_neto");

                    b.HasKey("Id");

                    b.ToTable("detalle_planilla");
                });

            modelBuilder.Entity("ExamenPOO_U2.Database.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER")
                        .HasColumnName("active");

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("TEXT")
                        .HasColumnName("base_salary");

                    b.Property<DateTime>("DateContratacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_contratacion");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT")
                        .HasColumnName("department");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("document");

                    b.Property<int>("JobPosition")
                        .HasColumnType("INTEGER")
                        .HasColumnName("job_position");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("ExamenPOO_U2.Database.Entities.PlanillaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_date");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("period");

                    b.Property<string>("State")
                        .HasColumnType("TEXT")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.ToTable("planilla");
                });
#pragma warning restore 612, 618
        }
    }
}
